### ISSUE TITLE
Broken Functionality: The Tray icon remains open after EncryptStore is closed

### ISSUE THREAD

**Issue by JustinGuerra** [encryptstore/EncryptStore#31]
**Describe the bug**
When the Close Button or Ctrl+c are used to stop EncryptStore the application window closes but its icon remains in the Tray(Dock) as an active application. The icon is removed from the Tray(Dock) after a SIGINT command is sent by force quitting the process.

**To Reproduce**
1. Enter "yarn start" in the command line
2. Hit Enter
3. Close the application using the Close Button or Ctrl+c
3a. To force kill the process press Alt+Command+Esc

**Expected behavior**
The icon should disappear from the Tray(Dock) after EncryptStore application has been closed using the Close Button or Ctrl+c from the terminal.

**Screenshots**
![image](https://user-images.githubusercontent.com/11654334/54243904-457e6400-44f8-11e9-9812-0452067194d6.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3

**Comment by JustinGuerra** [comment]
This is actually not a bug, but a design in the OS that allows the app to run even when all windows are closed. A comment will be left in the electron.js file for future reference.

**Comment by DanielHix** [comment]
We should also move the building and creation of the tray out of the electron.js file. You can either create the issue, or I'll do it myself later.
